export interface JarvisTheme {
  id: string;
  name: string;
  primary: string; // Hex color
  secondary: string; // Hex color
  description: string;
}

export const JARVIS_THEMES: JarvisTheme[] = [
  { id: "mk1-cyan", name: "MK1 Cyber Cyan", primary: "#00f3ff", secondary: "#020b18", description: "Classic high-tech azure interface." },
  { id: "mk2-emerald", name: "MK2 Emerald Matrix", primary: "#10b981", secondary: "#02180b", description: "Green phosphor tactical mode." },
  { id: "mk3-amber", name: "MK3 Amber Alert", primary: "#f59e0b", secondary: "#181002", description: "High-contrast gold visibility." },
  { id: "mk4-crimson", name: "MK4 Crimson Protocol", primary: "#f43f5e", secondary: "#180205", description: "Aggressive red-shift operational theme." },
  { id: "mk5-amethyst", name: "MK5 Amethyst Core", primary: "#a855f7", secondary: "#0f0218", description: "Deep intelligence purple mode." },
  { id: "mk6-cobalt", name: "MK6 Cobalt Deep", primary: "#3b82f6", secondary: "#020718", description: "Deep ocean blue tactical." },
  { id: "mk7-neon-pink", name: "MK7 Neon Synth", primary: "#ec4899", secondary: "#180210", description: "Synthwave pink aesthetic." },
  { id: "mk8-gold", name: "MK8 Sovereign Gold", primary: "#eab308", secondary: "#181402", description: "Royal gold command interface." },
  { id: "mk9-silver", name: "MK9 Quantum Silver", primary: "#94a3b8", secondary: "#0f1115", description: "Minimalist grayscale precision." },
  { id: "mk10-toxic", name: "MK10 Biohazard Green", primary: "#84cc16", secondary: "#0d1802", description: "High-vis toxic green." },
  { id: "mk11-plasma", name: "MK11 Plasma Orange", primary: "#f97316", secondary: "#180702", description: "Burning orange heat signature." },
  { id: "mk12-ice", name: "MK12 Absolute Zero", primary: "#67e8f9", secondary: "#021218", description: "Piercing bright ice blue." },
  { id: "mk13-void", name: "MK13 Dark Void", primary: "#4b5563", secondary: "#000000", description: "Stealth operations black/gray." },
  { id: "mk14-blood", name: "MK14 Blood Moon", primary: "#be123c", secondary: "#110000", description: "Deep dark red." },
  { id: "mk15-electric", name: "MK15 Electric Violet", primary: "#8b5cf6", secondary: "#0b0218", description: "Vibrant violet energy." },
  { id: "mk16-jade", name: "MK16 Imperial Jade", primary: "#14b8a6", secondary: "#021411", description: "Teal/Jade command grid." },
  { id: "mk17-sunset", name: "MK17 Solar Flare", primary: "#fb923c", secondary: "#180502", description: "Warm solar orange." },
  { id: "mk18-midnight", name: "MK18 Midnight Blue", primary: "#1d4ed8", secondary: "#010311", description: "Deepest blue tactical." },
  { id: "mk19-mint", name: "MK19 Quantum Mint", primary: "#6ee7b7", secondary: "#021811", description: "Soft high-vis mint." },
  { id: "mk20-rust", name: "MK20 Iron Rust", primary: "#b45309", secondary: "#180902", description: "Industrial rust orange." },
  { id: "mk21-coral", name: "MK21 Deep Coral", primary: "#fb7185", secondary: "#180207", description: "Vibrant coral pink." },
  { id: "mk22-indigo", name: "MK22 Indigo Pulse", primary: "#6366f1", secondary: "#050218", description: "Bright indigo tech." },
  { id: "mk23-lime", name: "MK23 Acid Lime", primary: "#a3e635", secondary: "#0a1802", description: "Blinding acid lime." },
  { id: "mk24-sky", name: "MK24 Stratosphere", primary: "#38bdf8", secondary: "#020f18", description: "Clear sky blue." },
  { id: "mk25-rose", name: "MK25 Dusty Rose", primary: "#e11d48", secondary: "#180206", description: "Muted tactical red." },
  { id: "mk26-slate", name: "MK26 Slate Armor", primary: "#64748b", secondary: "#080a0f", description: "Military slate gray." },
  { id: "mk27-fuchsia", name: "MK27 Fuchsia Drive", primary: "#d946ef", secondary: "#180216", description: "Intense fuchsia energy." },
  { id: "mk28-emerald-dark", name: "MK28 Dark Forest", primary: "#059669", secondary: "#011108", description: "Deep forest green." },
  { id: "mk29-amber-dark", name: "MK29 Burnt Amber", primary: "#d97706", secondary: "#110801", description: "Darkened amber." },
  { id: "mk30-cyan-dark", name: "MK30 Deep Ocean", primary: "#0891b2", secondary: "#010e11", description: "Dark cyan depths." },
  { id: "mk31-purple-dark", name: "MK31 Nebula", primary: "#7e22ce", secondary: "#0a0111", description: "Dark space purple." },
  { id: "mk32-pink-dark", name: "MK32 Dark Magenta", primary: "#be185d", secondary: "#110107", description: "Deep magenta core." },
  { id: "mk33-zinc", name: "MK33 Zinc Plating", primary: "#71717a", secondary: "#0a0a0a", description: "Neutral zinc gray." },
  { id: "mk34-stone", name: "MK34 Stone Guardian", primary: "#78716c", secondary: "#0f0e0d", description: "Warm stone gray." },
  { id: "mk35-red", name: "MK35 Pure Red", primary: "#dc2626", secondary: "#110101", description: "Standard alert red." },
  { id: "mk36-blue", name: "MK36 Pure Blue", primary: "#2563eb", secondary: "#020711", description: "Standard tactical blue." },
  { id: "mk37-green", name: "MK37 Pure Green", primary: "#16a34a", secondary: "#021105", description: "Standard success green." },
  { id: "mk38-yellow", name: "MK38 Pure Yellow", primary: "#ca8a04", secondary: "#110c01", description: "Standard warning yellow." },
  { id: "mk39-teal", name: "MK39 Pure Teal", primary: "#0d9488", secondary: "#01110f", description: "Standard balanced teal." },
  { id: "mk40-orange", name: "MK40 Pure Orange", primary: "#ea580c", secondary: "#110501", description: "Standard action orange." },
  { id: "mk41-cyan-light", name: "MK41 Ghost Cyan", primary: "#a5f3fc", secondary: "#021518", description: "Ultra-light ghost cyan." },
  { id: "mk42-emerald-light", name: "MK42 Ghost Emerald", primary: "#a7f3d0", secondary: "#02180e", description: "Ultra-light ghost green." },
  { id: "mk43-amber-light", name: "MK43 Ghost Amber", primary: "#fde68a", secondary: "#181402", description: "Ultra-light ghost gold." },
  { id: "mk44-rose-light", name: "MK44 Ghost Rose", primary: "#fecdd3", secondary: "#18060a", description: "Ultra-light ghost red." },
  { id: "mk45-purple-light", name: "MK45 Ghost Purple", primary: "#e9d5ff", secondary: "#120218", description: "Ultra-light ghost purple." },
  { id: "mk46-obsidian", name: "MK46 Obsidian Tech", primary: "#52525b", secondary: "#000000", description: "Black and dark gray." },
  { id: "mk47-copper", name: "MK47 Oxidized Copper", primary: "#5eead4", secondary: "#021815", description: "Patina copper green." },
  { id: "mk48-brass", name: "MK48 Polished Brass", primary: "#fcd34d", secondary: "#181102", description: "Bright brass yellow." },
  { id: "mk49-steel", name: "MK49 Damascus Steel", primary: "#cbd5e1", secondary: "#0d1118", description: "Layered steel gray." },
  { id: "mk50-hologram", name: "MK50 True Hologram", primary: "#ccffff", secondary: "#001118", description: "Pure white-blue hologram." },
  { id: "mk51-supernova", name: "MK51 Supernova", primary: "#ffffff", secondary: "#110000", description: "Blinding white on dark red." },
];
